/**
 * Mock data for volunteer portal UI development.
 * Replace with real API calls once the backend is wired up.
 */

export const DAYS = [
  { label: 'Mon', date: '2026-05-04', full: 'Monday, May 4' },
  { label: 'Tue', date: '2026-05-05', full: 'Tuesday, May 5' },
  { label: 'Wed', date: '2026-05-06', full: 'Wednesday, May 6' },
  { label: 'Thu', date: '2026-05-07', full: 'Thursday, May 7' },
  { label: 'Fri', date: '2026-05-08', full: 'Friday, May 8' },
];

// Role names volunteers can select at onboarding
export const ROLES = [
  'Room Runner',
  'Registration & Check-In',
  'Door Monitor',
  'Building Runner',
  'Session Host',
  'A/V & Tech Support',
  'Wayfinding',
  'Social Media',
  'Venue Setup',
  'Green Room',
];

// Info bubble copy shown on each shift card
export const ROLE_INFO = {
  'Room Runner': 'Set up chairs, hang banners, and prep the room before sessions start. You\'re the reason everything looks right when doors open.',
  'Registration & Check-In': 'Greet attendees, scan tickets, and hand out lanyards. First impression of the whole week — make it warm.',
  'Door Monitor': 'Manage crowd flow, direct attendees to their seats, and keep things orderly when sessions are at capacity.',
  'Building Runner': 'General facility support across the venue. Moving supplies, troubleshooting logistics, helping wherever things are tight.',
  'Session Host': 'Introduce speakers, manage Q&A, and keep sessions on time. You\'re the glue between the audience and the stage.',
  'A/V & Tech Support': 'Set up mics, projectors, and livestream. Experience with AV gear required. Arrive 30 min early for setup.',
  'Wayfinding': 'Stand at key intersections and guide attendees between venues. Know your way around downtown Boulder.',
  'Social Media': 'Live-tweet sessions, capture highlights, post stories to BSW channels. Bring your own phone and a charger.',
  'Venue Setup': 'Chairs, tables, signage, and final touches before doors open. Early bird shift — coffee provided.',
  'Green Room': 'Support speakers before they go on. Keep the space calm, stocked, and running smoothly.',
};

export const LOCATIONS = [
  'Boulder Theater — Main Entrance',
  'Boulder Theater — Main Stage',
  'Boulder Theater — Green Room',
  'Boulder Theater',
  'Rembrandt Yard',
  'Rembrandt Yard — Entrance',
  'Rembrandt Yard — Summit Stage',
  'Downtown Boulder — Various',
  'All Venues',
];

export const SHIFTS = [
  {
    id: 'shift-1',
    role: 'Registration & Check-In',
    day: '2026-05-04',
    start_time: '07:30',
    end_time: '09:30',
    location: 'Boulder Theater — Main Entrance',
    total_slots: 6,
    filled_slots: 4,
    description: 'Welcome attendees and hand out badges. You\'ll be the first face people see — make it count.',
    signed_up_names: ['Mia Torres', 'Dev Patel', 'Jordan Kim', 'Sarah Chen'],
  },
  {
    id: 'shift-2',
    role: 'Room Runner',
    day: '2026-05-04',
    start_time: '08:00',
    end_time: '10:00',
    location: 'Boulder Theater — Main Stage',
    total_slots: 3,
    filled_slots: 1,
    description: 'Set up the main stage before the morning sessions. Chairs, signage, and a final walkthrough.',
    signed_up_names: ['Marcus Webb'],
  },
  {
    id: 'shift-3',
    role: 'A/V & Tech Support',
    day: '2026-05-04',
    start_time: '07:00',
    end_time: '09:00',
    location: 'Rembrandt Yard',
    total_slots: 4,
    filled_slots: 2,
    description: 'Set up mics, projectors, and livestream. Experience with AV gear required.',
    signed_up_names: ['Priya Nair', 'Dev Patel'],
  },
  {
    id: 'shift-4',
    role: 'Door Monitor',
    day: '2026-05-04',
    start_time: '09:00',
    end_time: '11:00',
    location: 'Boulder Theater — Main Stage',
    total_slots: 4,
    filled_slots: 2,
    description: 'Manage crowd flow for the opening keynote. Expect a packed room.',
    signed_up_names: ['Jordan Kim', 'Sarah Chen'],
  },
  {
    id: 'shift-5',
    role: 'Wayfinding',
    day: '2026-05-05',
    start_time: '08:00',
    end_time: '10:00',
    location: 'Downtown Boulder — Various',
    total_slots: 8,
    filled_slots: 3,
    description: 'Stand at key intersections and guide attendees between venues.',
    signed_up_names: ['Mia Torres', 'Marcus Webb', 'Jordan Kim'],
  },
  {
    id: 'shift-6',
    role: 'Registration & Check-In',
    day: '2026-05-05',
    start_time: '07:30',
    end_time: '09:30',
    location: 'Rembrandt Yard — Entrance',
    total_slots: 4,
    filled_slots: 4,
    description: 'Day two check-in. Expect returning faces and new ones — keep the energy up.',
    signed_up_names: ['Dev Patel', 'Sarah Chen', 'Priya Nair', 'Mia Torres'],
  },
  {
    id: 'shift-7',
    role: 'Green Room',
    day: '2026-05-05',
    start_time: '09:00',
    end_time: '11:00',
    location: 'Boulder Theater — Green Room',
    total_slots: 2,
    filled_slots: 0,
    description: 'Support speakers before they go on. Keep the space calm, stocked, and running smoothly.',
    signed_up_names: [],
  },
  {
    id: 'shift-8',
    role: 'Building Runner',
    day: '2026-05-06',
    start_time: '08:00',
    end_time: '10:00',
    location: 'All Venues',
    total_slots: 5,
    filled_slots: 2,
    description: 'Move supplies, run errands, support whatever the team needs midweek.',
    signed_up_names: ['Jordan Kim', 'Marcus Webb'],
  },
  {
    id: 'shift-9',
    role: 'Room Runner',
    day: '2026-05-06',
    start_time: '10:00',
    end_time: '12:00',
    location: 'Rembrandt Yard',
    total_slots: 4,
    filled_slots: 4,
    description: 'Wednesday midday room setup. Quick turnaround between sessions.',
    signed_up_names: ['Mia Torres', 'Dev Patel', 'Sarah Chen', 'Priya Nair'],
  },
  {
    id: 'shift-10',
    role: 'Social Media',
    day: '2026-05-07',
    start_time: '09:00',
    end_time: '11:00',
    location: 'All Venues',
    total_slots: 2,
    filled_slots: 1,
    description: 'Live-tweet sessions, capture highlights, post stories. Bring your own phone + charger.',
    signed_up_names: ['Sarah Chen'],
  },
  {
    id: 'shift-11',
    role: 'Door Monitor',
    day: '2026-05-07',
    start_time: '13:00',
    end_time: '15:00',
    location: 'Boulder Theater — Main Stage',
    total_slots: 3,
    filled_slots: 0,
    description: 'Thursday afternoon session crowd management. High-traffic period.',
    signed_up_names: [],
  },
  {
    id: 'shift-12',
    role: 'Venue Setup',
    day: '2026-05-08',
    start_time: '06:00',
    end_time: '08:00',
    location: 'Boulder Theater',
    total_slots: 6,
    filled_slots: 1,
    description: 'Chairs, tables, signage, and final touches before doors open. Early bird shift — coffee provided.',
    signed_up_names: ['Priya Nair'],
  },
  {
    id: 'shift-13',
    role: 'Session Host',
    day: '2026-05-08',
    start_time: '13:00',
    end_time: '15:00',
    location: 'Rembrandt Yard — Summit Stage',
    total_slots: 3,
    filled_slots: 0,
    description: 'Host the closing afternoon sessions on the last day. Go out strong.',
    signed_up_names: [],
  },
  {
    id: 'shift-14',
    role: 'Registration & Check-In',
    day: '2026-05-08',
    start_time: '07:30',
    end_time: '09:30',
    location: 'Rembrandt Yard — Entrance',
    total_slots: 4,
    filled_slots: 2,
    description: 'Final day check-in. Keep the energy high for the closing day.',
    signed_up_names: ['Mia Torres', 'Dev Patel'],
  },
];

// Mock: days this volunteer is available (normally comes from their profile)
export const MY_AVAILABILITY = ['2026-05-04', '2026-05-05', '2026-05-07'];

export const MY_SHIFTS = [SHIFTS[0], SHIFTS[4], SHIFTS[9]];

export const VOLUNTEERS = [
  {
    id: 'v1',
    name: 'Mia Torres',
    email: 'mia@example.com',
    phone: '(720) 555-0101',
    availability: ['2026-05-04', '2026-05-05', '2026-05-07'],
    shift_count: 3,
    status: 'confirmed',
  },
  {
    id: 'v2',
    name: 'Dev Patel',
    email: 'dev@example.com',
    phone: '(720) 555-0102',
    availability: ['2026-05-04', '2026-05-06', '2026-05-07'],
    shift_count: 2,
    status: 'confirmed',
  },
  {
    id: 'v3',
    name: 'Jordan Kim',
    email: 'jordan@example.com',
    phone: '(303) 555-0103',
    availability: ['2026-05-05', '2026-05-06'],
    shift_count: 2,
    status: 'confirmed',
  },
  {
    id: 'v4',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    phone: '(720) 555-0104',
    availability: ['2026-05-07', '2026-05-08'],
    shift_count: 1,
    status: 'pending',
  },
  {
    id: 'v5',
    name: 'Marcus Webb',
    email: 'marcus@example.com',
    phone: '(303) 555-0105',
    availability: ['2026-05-04', '2026-05-05', '2026-05-08'],
    shift_count: 1,
    status: 'pending',
  },
  {
    id: 'v6',
    name: 'Priya Nair',
    email: 'priya@example.com',
    phone: '(720) 555-0106',
    availability: ['2026-05-08'],
    shift_count: 2,
    status: 'confirmed',
  },
];

export const ADMIN_STATS = {
  total_volunteers: 47,
  total_shifts: 24,
  filled_shifts: 16,
  open_shifts: 8,
  fill_rate: 67,
  confirmed_volunteers: 31,
  pending_volunteers: 16,
};
